#!/bin/bash

src=nbprojlink

rsync -rtv $@ --exclude war/hello* \
              --exclude war/WEB-INF/classes* \
              --exclude war/WEB-INF/lib* \
              --exclude nbproject* \
              --exclude nbprojlink* \
              --exclude projsync* \
              --exclude .gitignore* \
  ${src}/  ./

